services:
  php:
    image: php-fpm:8.1
    build:
      context: ./dockerfiles/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    deploy:
      replicas: 3
    volumes:
      - ./app:/var/www/devops-demo
    working_dir: /var/www/devops-demo
    networks:
      - lab2-net
  nginx:
    image: nginx:1.23
    container_name: devops-demo-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/devops-demo
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - lab2-net
  db:
    image: mysql:8.0
    container_name: devops-demo-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
    working_dir: /var/www/devops-demo
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - lab2-net
volumes:
  mysql_data:
    external: true
networks:
  lab2-net:
