apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  duration: 8760h
  renewBefore: 360h
  dnsNames:
    - devops-demo.local
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned
